### PR TITLE
Lazy stream version

### PR DESCRIPTION
**Pull request by chrisortman**
Allows for any sequence of nums and should operate in constant memory space (no stack recursion)

### CODE REVIEW

**Comment by chrisortman** [comment]
I do not understand why I cannot add a reviewer :/

**Comment by benjaminoakes** [comment]
> I do not understand why I cannot add a reviewer :/

I'm not sure either, but I just added you as a collaborator to see if that will help.

**Comment by benjaminoakes** [comment]
> Allows for any sequence of nums and should operate in constant memory space (no stack recursion)

The [tail-recursive solution](https://github.com/techcorridorio/euler-elixir/commit/d3056b73054f80d4ebf0d7bdcdaa4ccd166ed020) should run in constant space too, right?

**Comment by chrisortman** [comment]
Yes

**Pull request merged**
